name: Cafe Zrno
baseurl: /cafe-zrno
description: Kafana u Podgoricu

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
